name: GitAuto

on:
  schedule:
    - cron: "30 */2 * * *"
  workflow_dispatch:
    inputs:
      test:
        description: "Test latest episode detection now"
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install feedparser requests

      - name: Run script
        env:
          TEST_SEND: ${{ github.event.inputs.test }}
        run: python gitauto.py

      - name: Zip podcasts folder with date
        run: |
          TODAY=$(date +'%Y-%m-%d')
          zip -r "podcasts-auto-$TODAY.zip" podcasts_auto/

      - name: Upload to GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create auto-podcast-releases --title "Auto Daily Podcast Archives" --notes "Automated archives of downloaded podcast episodes." || true
          TODAY=$(date +'%Y-%m-%d')
          gh release upload auto-podcast-releases "podcasts-auto-$TODAY.zip" --clobber

      - name: Remove large files locally before Git commit
        run: |
          find podcasts_auto/ -type f -size +95M -exec rm -f {} +

      - name: Save state and files to Git
        run: |
          git config user.name "bot"
          git config user.email "bot@users.noreply.github.com"
          git add seen.json podcasts_auto/
          git diff --cached --quiet || (git commit -m "Add auto podcast episodes and update state" && git push)
